# Generated by Django 5.2.17 on 2026-08-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_document_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("ocr_processing", "OCR processing"),
                    ("ocr_completed", "OCR completed"),
                    ("verified", "Verified"),
                    ("error", "Error"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
    ]
