# Generated by Django 5.2.17 on 2026-08-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_ocrresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrresult",
            name="processing_time_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
