# Generated by Django 5.2.17 on 2026-08-19 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_file_hash_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('amount_without_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='documents.document')),
            ],
            options={
                'ordering': ['line_number'],
                'constraints': [models.UniqueConstraint(fields=('document', 'line_number'), name='unique_document_line_number')],
            },
        ),
    ]
