# Generated by Django 5.2.17 on 2026-08-14 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(blank=True, max_length=255)),
                ("inn", models.CharField(max_length=12)),
                ("kpp", models.CharField(blank=True, max_length=9)),
                ("bank_account", models.CharField(blank=True, max_length=20)),
                ("bik", models.CharField(blank=True, max_length=9)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suppliers",
                        to="companies.company",
                    ),
                ),
            ],
        ),
    ]
