# Generated by Django 5.2.16 on 2026-08-13 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0006_documentfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('warning', 'Warning'), ('failed', 'Failed'), ('not_applicable', 'Not applicable'), ('insufficient_data', 'Insufficient data')], max_length=32)),
                ('severity', models.CharField(max_length=16)),
                ('score', models.IntegerField(default=0)),
                ('actual_value', models.JSONField(blank=True, null=True)),
                ('expected_value', models.JSONField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_results', to='documents.document')),
            ],
        ),
    ]
